#!/bin/bash

# Script to remove CocoaPods artifacts after migrating to Swift Package Manager
# This script should be run AFTER adding dependencies via Swift Package Manager in Xcode

set -e

echo "🚀 CocoaPods Cleanup Script for SPM Migration"
echo "=============================================="
echo ""

# Check if we're in the right directory
if [ ! -f "Podfile" ]; then
    echo "❌ Error: Podfile not found. Are you in the project root directory?"
    exit 1
fi

echo "⚠️  WARNING: This script will remove CocoaPods files."
echo "Make sure you have:"
echo "  1. Already added Swift Package Manager dependencies in Xcode"
echo "  2. Verified the project builds successfully with SPM"
echo "  3. Backed up your project (or committed to git)"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled."
    exit 0
fi

echo ""
echo "📦 Removing CocoaPods files..."

# Remove Podfile and lock file
if [ -f "Podfile" ]; then
    echo "  - Removing Podfile"
    rm Podfile
fi

if [ -f "Podfile.lock" ]; then
    echo "  - Removing Podfile.lock"
    rm Podfile.lock
fi

# Remove Pods directory
if [ -d "Pods" ]; then
    echo "  - Removing Pods directory"
    rm -rf Pods/
fi

# Remove workspace (optional)
echo ""
read -p "Remove .xcworkspace? (This is generated by CocoaPods) (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    if [ -d "SzContext.xcworkspace" ]; then
        echo "  - Removing SzContext.xcworkspace"
        rm -rf SzContext.xcworkspace/
    fi
fi

echo ""
echo "✅ CocoaPods cleanup complete!"
echo ""
echo "Next steps:"
echo "  1. Open SzContext.xcodeproj (not .xcworkspace)"
echo "  2. Build and test the project"
echo "  3. Commit the changes to git"
echo ""
echo "If you encounter issues, you can restore from git:"
echo "  git checkout -- ."
echo "  pod install"
echo ""
